# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
#- master

pool:
  vmImage: ubuntu-latest
variables:
 resourceGroupName: "APIM-DEVOPS"
 location: "eastus"
 APP_NAME: "solar201"
 APP_ENV: "dev"  
 imageName: "compliancewebapi"
 tag: "$(Build.BuildId)"
 registryname: "$(APP_NAME)contregistry$(APP_ENV)"
 registry: "$(APP_NAME)contregistry$(APP_ENV).azurecr.io"
 imageRepository: "compliancewebapi"
 ComplianceWebApi_Path: "/src/WebApis/ComplianceWebApi/"
 dockerfilePath: "src/WebApis/ComplianceWebApi/Dockerfile"



steps:
# Create Core Infra stucture
# - task: AzureCLI@2
#   displayName: Create Core Infrastructure
#   inputs:
#     azureSubscription: 'masterconnection'
#     scriptType: 'bash'
#     scriptLocation: 'scriptPath'
#     scriptPath: 'Infrastructure/Platform/create-core-infra.sh'

# - task: AzureCLI@2
#   inputs:
#     azureSubscription: 'masterconnection'
#     scriptType: 'bash'
#     scriptLocation: 'inlineScript'
#     inlineScript: |
     
#       echo "Login to Azure Container Registry"
#       accessToken=$(az acr login --name $(registry) --expose-token --output tsv --query accessToken)
#       docker login $(registry) --username 00000000-0000-0000-0000-000000000000 --password $accessToken
      
#       echo "Building Images with Tag '${imageName}:${tag}'"
#       docker build -t $(registry)/$(imageName):$(tag) -f ./src/WebApis/ComplianceWebApi/Dockerfile .
      
#       echo "Pushing to '$registry'"
#       docker push $(registry)/$(imageName):$(tag)
# Build docker image for ComplianceWebApi and push to Azure container registry
- task: AzureCLI@2
  displayName: Create Core Infrastructure
  inputs:
    azureSubscription: 'masterconnection'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'    
    scriptPath: 'Infrastructure/ContainerImages/buildpushdockerimage.sh'
    arguments: '$(registry) $(registryname) $(imageName) $(tag) $(APP_NAME) $(APP_ENV)'
 

            




       






