parameters:
  - name: agentPool
    type: string
    default: Rabo-Linux-Production
  - name: azureSubscription
    type: string
  - name: keyVaultName
    type: string
  - name: secrets 
    type: object 
  - name: env 
    type: object 
  - name: beforeSecretsUpdate
    type: stepList
    default: []
  - name: environment
    type: string
    default: azdo-test

jobs:
  - deployment: UpdateSecrets
    displayName: Update secrets
    pool: ${{parameters.agentPool}}
    environment: ${{parameters.environment}}
    strategy:
      runOnce:
        deploy:
          steps:
            - ${{ parameters.beforeSecretsUpdate }}
            - ${{ each secret in parameters.secrets }}: 
              - template: ../task/keyvault-secret-set-task.yml
                parameters:
                  azureSubscription: ${{parameters.azureSubscription}}
                  keyVaultName: ${{parameters.keyVaultName}}
                  name: ${{secret.name}}
                  value: ${{secret.value}}
                  env: ${{parameters.env}}